name: Weekly Feedfry Emailer

on:
  schedule:
    - cron: '0 6 * * 0'  # Runs every Sunday at 6 AM UTC
  workflow_dispatch:      # Allows manual runs too

jobs:
  run-feed-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps

      - name: Run Feedfry script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}   # ✅ This was missing
        run: python main.py
